### ISSUE TITLE
Set I and you correctly based on spin

### ISSUE THREAD

**Issue by anjchang** [nickmontfort/curveship-js#26]
When `spin`(as it appears at the top of the narrator file) has the keys `i` or `you` set and their values are Actors, these Actors become who is telling the narrative and to whom the narrative is told during realization.  That is, first person pronouns replace the `i` Actor, and second person pronouns replace the `you` Actor.

**Comment by nickmontfort** [comment]
Added `test/spin` and the `personal.js` narrator file, which will be realized properly when this bug is fixed.
There's no support for i/you in the 0.4 code now, but this worked in earlier versions of Curveship-js and must work for learning purposes in September.

**Comment by anjchang** [comment]
Just documenting that the format is to set spin using strings for character names (which are the suffix fo the name).
<pre>var spin = {
   i: "fox",
   you: "henny"
};
</pre>

**Comment by nickmontfort** [comment]
These aren't character names. They are the *tags* of Actors. There are no "characters" conceptually in Curveship, only Actors. You find Names in different objects that can optionally be defined to align with Existents. In fact actor.mary has no Names defined and GenericNames are used as a fallback. "john" and "mary" are the tags given to these two Actors, actor.john and actor.mary.
