### ISSUE TITLE
subject verb agreement with categories

### ISSUE THREAD

**Issue by anjchang** [nickmontfort/curveship-js#27]
Realizing a `category` must preserve subject-verb agreement. If the category name ends with an 's' the verb should be singular. For example "The animals laugh." "The crowd laughs."

**Comment by nickmontfort** [comment]
Inspecting the way a Category name is realized to see if the last letter is "s" does not resolve this issue. That would result in "the princess laugh" and "the children laughs." Curveship always needs to use a complete and robust approach to pluralization and (for instance) determining whether "a" or "an" is the indefinite article to use.

However, this does not manifest itself as a problem if all Categories have singular names. For now we will require this, just as we require all Existents to be singular. A dog, for instance, is in the Category "animal" with a singular name, while an Actor will be in the Category "human" with a singular name. Then, when pluralization of a Category name needs to be done it will be done through the complete, robust process in `noun.js`.
