### ISSUE TITLE
Event/Object/Uncapitalized

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#32]
It just caught my eye that when we are using an event as another event's object, the subject of that event is still written capitalized in the middle of a sentence. ("He does not know that **_It_** crashes", _The Story of an Hour_)

**Comment by nickmontfort** [comment]
Yes, and there is also an extra period.

**Comment by nickmontfort** [comment]
Oops, under some circumstances this will not work. I had the system always lowercase the first letter of the embedded sentence (the sentence representing the event that is a participant). But if this sentence begins with a proper noun, the capitalization needs to be preserved. So something more complex needs to be done here.
