### ISSUE TITLE
Verb Tense Change Issue

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#60]
I encountered an issue while changing order of events in _Waiting_ example.
"He does not shout," changed to "He had done not shout"

**Comment by nickmontfort** [comment]
The existing capacity for negated events was not being used here (or in Prodigal, or in Hour). I have fixed this now. It's possible there are still some problems with negated events, but a retrograde ordering now results in negated events being realized properly, at least, so I'll close this.
