### ISSUE TITLE
Pluralizing Servants

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#61]
@nickmontfort I remember when I had earlier submitted this issue you responded that you'd put the servants into a category after you go through that variable. I'm not sure whether it was intentionally left unchanged, but currently, the event still is generated as "He inquires of the servant, the servant, and the servant" instead of "He inquires of the servants". I didn't change anything in case you didn't mean to alter it now.

**Comment by nickmontfort** [comment]
Yes, the servants need to be in a category, the category needs a name, and grouping by category needs to be on. Fixed now.
