### ISSUE TITLE
Minor Tense Issue

### ISSUE THREAD

**Issue by arthalun** [nickmontfort/curveship-js#62]
When I changed the order of representing events in the _Prodigal_ example, I encountered that the verb "run" changed to "ran" instead of "run" in its past participle form.

**Comment by nickmontfort** [comment]
This is a tricky one! There are actually two ways to conjugate "ran." "The water had ran out" sounds correct to me correct but "He had run to his son" also sounds correct. In verb.js these are represented as "run" and "run2". For now, to avoid introducing this rare case in the examples, I have switched run and run2. If an author wants to use the other conjugation of run, the verb should be given as "run2".

You can see that there are a few other cases like this in verb.js if you search for 2" in the file.
